---
# tasks file for controller
- name: install controller packages
  apt:
    update_cache: yes
    name:
      - git
      - lolcat
    state: present

- name: disable ssh host key checking
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"
    regexp: "StrictHostKeyChecking"
    state: present