---
# tasks file for controller
- name: Install Controller Packages
  apt:
    update_cache: yes
    name:
      - git
      - lolcat
      - slurmd
    state: present

- name: disable ssh host key checking
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"
    regexp: "StrictHostKeyChecking"
    state: present

- name: point DNS at the Headnode
  lineinfile:
    path: /etc/systemd/resolved.conf
    line: "DNS=${headnodeip}"
    regexp: "DNS="
    state: present

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted