---
- name: Ensure RDMA packages are installed
  package:
    name: "{{ beegfs_distro_vars[ansible_os_family]['rdma_dev_pkgs'] }}"
    state: present
  become: true

- name: Ensure RDMA kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "ib_umad"
    - "ib_uverbs"
    - "rdma_ucm"
...
