---
# Tasks file for common tasks across all systems. 

- name: Update package cache 
  apt: 
    update_cache: yes
    cache_valid_time: 3600

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3-pymysql
    - python3-pip

- name: Create symbolic link for Python
  file:
    src: "/usr/bin/python3"
    dest: "/usr/bin/python"
    state: link

- name: Create symbolic link for Python-pip
  file:
    src: "/usr/bin/pip3"
    dest: "/usr/bin/pip"
    state: link

  # Appending hosts to the /etc/hosts file.
- name: update host file 
  lineinfile:
    path: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  become: yes
  with_items: "{{ groups.all }}"

- name: disable ssh host key checking
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"
    regexp: "StrictHostKeyChecking"
    state: present