---
# tasks file for common

- name: Update package cache 
  apt: 
    update_cache: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3-pymysql

- name: Inserting alias for python 
  lineinfile:
    path: ~/.bashrc
    line: alias python='python3'
    insertafter: alias.*

# Appending hosts to the /etc/hosts file.
- name: update host file 
  lineinfile:
    path: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  become: yes
  with_items: "{{ groups.all }}"

- name: disable ssh host key checking
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"
    regexp: "StrictHostKeyChecking"
    state: present