---
# tasks file for common

# Appending hosts to the /etc/hosts file.
- name: update host file 
  lineinfile:
    path: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  become: yes
  with_items: "{{ groups.all }}"