---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    options:
      cpus: 1
      memory: 1024
lint:
  name: yamllint
  # enabled: false
platforms:
  - name: centos7.5-vagrant
    box: bento/centos-7.5
    # interfaces:
    #   - network_name: private_network
    #     type: dhcp
    #     auto_config: true
    provider_raw_config_args:
      - "customize ['createhd', '--filename', '/tmp/beegfsDisk-centos.vdi', '--size', 50 * 1024]"
      - "customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', '/tmp/beegfsDisk-centos.vdi']"
    groups:
      - cluster_beegfs_mgmt
      - cluster_beegfs_mds
      - cluster_beegfs_oss
      - cluster_beegfs_client
  - name: ubuntu16.04-vagrant
    box: bento/ubuntu-16.04
    # interfaces:
    #   - network_name: private_network
    #     type: dhcp
    #     auto_config: true
    provider_raw_config_args:
      - "customize ['createhd', '--filename', '/tmp/beegfsDisk-ubuntu.vdi', '--size', 50 * 1024]"
      - "customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', '/tmp/beegfsDisk-ubuntu.vdi']"
    groups:
      - cluster_beegfs_mgmt
      - cluster_beegfs_mds
      - cluster_beegfs_oss
      - cluster_beegfs_client
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    # enabled: false
    options:
      R: true
scenario:
  name: vagrant-all
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: true
  lint:
    name: flake8
