---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible molecule

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Compensate for repo name being different to the role
  - ln -s ansible-role-beegfs ../stackhpc.beegfs

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Molecule linting checks
  - molecule lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
