---

- hosts: all
  roles:
    - common
    - geerlingguy.ntp
    
- hosts: controller
  roles:
    - geerlingguy.mysql

- hosts: headnode
  roles: 

- hosts: workernodes
  roles:

# SLURM - Role layout of StackHPC - https://github.com/stackhpc/ansible-role-openhpc
- hosts:
  - controller
  - headnode
  - workernodes
  become: yes
  roles:
    - role: ansible-role-slurm
      slurm_enable:
        controller: "{{ inventory_hostname in groups['controller'] }}"
        headnode: "{{ inventory_hostname in groups['headnode'] }}"
        compute: "{{ inventory_hostname in groups['workernodes'] }}"

# BeeGFS - Role layout of StackHPC - https://github.com/stackhpc/ansible-role-beegfs
- hosts:
  - cluster_beegfs_mgmt
  - cluster_beegfs_mds
  - cluster_beegfs_oss
  - cluster_beegfs_client
  roles:
  - role: ansible-role-beegfs
    beegfs_enable:
      admon: false
      mgmt: "{{ inventory_hostname in groups['cluster_beegfs_mgmt'] }}"
      meta: "{{ inventory_hostname in groups['cluster_beegfs_mds'] }}"
      oss: "{{ inventory_hostname in groups['cluster_beegfs_oss'] }}"
      tuning: "{{ inventory_hostname in groups['cluster_beegfs_oss'] }}"
      client: "{{ inventory_hostname in groups['cluster_beegfs_client'] }}"
    beegfs_oss:
    - dev: "/dev/vdb"
      port: 8003
    - dev: "/dev/vdc"
      port: 8103
    - dev: "/dev/vdd"
      port: 8203
    beegfs_mgmt_host: "{{ groups['cluster_beegfs_mgmt'] | first }}"
    beegfs_client:
    - path: "/beegfs"
      port: 8004
    beegfs_fstype: "xfs"
    beegfs_force_format: false
    beegfs_interfaces: ["ens3"]
    beegfs_rdma: false
    beegfs_state: present
    
    