---
# Tasks for Worker Nodes
- name: Install WorkerNode Packages
  apt:
    name:
      - git
      - lolcat
      - slurmd
    state: present

- name: disable ssh host key checking
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"
    regexp: "StrictHostKeyChecking"
    state: present